// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKCkxPfFLZipJTZ_9s5zUXtwpydFZHzkU',
    appId: '1:1052868417560:web:c5f8fef1bc656193608b6d',
    messagingSenderId: '1052868417560',
    projectId: 'eventmaster-rcet',
    authDomain: 'eventmaster-rcet.firebaseapp.com',
    storageBucket: 'eventmaster-rcet.appspot.com',
    measurementId: 'G-99YZ5T4S9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi19t6XrWQUAfvQh9_cjfpHjMvpxcX3pc',
    appId: '1:1052868417560:android:7087b2c42f233fc3608b6d',
    messagingSenderId: '1052868417560',
    projectId: 'eventmaster-rcet',
    storageBucket: 'eventmaster-rcet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9uBsFGT8H8pHrrbbfrpI1pHt4QV-1bgM',
    appId: '1:1052868417560:ios:eb4e764fccf8dd91608b6d',
    messagingSenderId: '1052868417560',
    projectId: 'eventmaster-rcet',
    storageBucket: 'eventmaster-rcet.appspot.com',
    iosBundleId: 'com.example.eventMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9uBsFGT8H8pHrrbbfrpI1pHt4QV-1bgM',
    appId: '1:1052868417560:ios:eb4e764fccf8dd91608b6d',
    messagingSenderId: '1052868417560',
    projectId: 'eventmaster-rcet',
    storageBucket: 'eventmaster-rcet.appspot.com',
    iosBundleId: 'com.example.eventMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKCkxPfFLZipJTZ_9s5zUXtwpydFZHzkU',
    appId: '1:1052868417560:web:fac9f589ad32e600608b6d',
    messagingSenderId: '1052868417560',
    projectId: 'eventmaster-rcet',
    authDomain: 'eventmaster-rcet.firebaseapp.com',
    storageBucket: 'eventmaster-rcet.appspot.com',
    measurementId: 'G-W6H530Q1GH',
  );
}
